title: Kişisel Portal
description: Bu alanda düşüncelerimi, projelerimi ve günlük notlarımı paylaşıyorum.
baseurl: "" # Eğer siten kullanıcıadı.github.io/repo-adi şeklinde açılıyorsa buraya "/repo-adi" yaz
url: ""

markdown: kramdown
theme: null
