title: Hastane Portal
description: İş hayatında kullanmak üzere oluşturulmuş yardımcı internet sayfasıdır.
baseurl: "/hastane" # Eğer siten kullanıcıadı.github.io/repo-adi şeklinde açılıyorsa buraya "/repo-adi" yaz
url: ""

markdown: kramdown
theme: null
